# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: EDV CI

on:
  pull_request:
  push:

jobs:
  edv_workflow_tests:
    name: EDV workflow tests
    # container: nrel/openstudio:3.0.1
    runs-on: ubuntu-latest

    steps:
    - name: checkout v2
      uses: actions/checkout@v2
    - name: ruby version
      uses: ruby/setup-ruby@v1 
      with:
        ruby-version: 2.5.5
    # - name: Rubocop
    #   run: |
    #     sudo gem install rubocop
    #     rubocop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Workflow set up
      run: |
        sudo gem install bundler
        bundle install
    - name: Initial test spec
      run: bundle exec rspec spec/tests/initial_spec.rb
      if: always()
#     - name: Add measured data spec
#       run: bundle exec rspec spec/tests/add_measured_data_spec.rb
#       if: always()
#     - name: Driving scripts spec
#       run: bundle exec rspec spec/tests/driving_scripts_spec.rb
#       if: always()
#     - name: Experiment spec
#       run: bundle exec rspec spec/tests/experiment_spec.rb
#       if: always()
#     - name: Metrics calculation spec
#       run: bundle exec rspec spec/tests/metrics_calculation_spec.rb
#       if: always()
#     - name: Occupancy simulator spec
#       run: bundle exec rspec spec/tests/occupancy_simulator_spec.rb
#       if: always()
