# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: EDV CI

on:
  push:
  pull_request:

jobs:
  sanity_check:
    name: EDV workflow tests
    # container: nrel/openstudio:3.0.1
    runs-on: ubuntu-latest

    steps:
    - name: checkout v2
      uses: actions/checkout@v2
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
    - uses: ruby/setup-ruby@v1 
      with:
        ruby-version: 2.5.5
    - name: Workflow set up
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      run: |
        ruby --version
        sudo gem install bundler
        bundle install
    - name: Initial test
      run: | 
        bundle exec rspec ./../spec/tests/initial_test.rb
      if: always()
